import me from 'images/bangkok.jpeg'
import ContentBox from 'main/components/contentBox/ContentBox'
import Welcome from 'main/components/welcome/Welcome'

import './Home.css'

const ABOUT_TEXT = "I graduated from university in 2021, leaving with a 2:1 in Computer Science. For me, university was an experience to deepen my understanding of software development, as I had already had an interest in computers from a young age. This started from me getting my first personal computer at the age of six, and quickly trying to find ways to recreate my favourite games. That started with me introducing myself to HTML not long after starting secondary school, to then toying with the Unity game engine and using UnityScript to create presentations in a 3D environment. From there, I was introduced to Java as I looked deeper into game development and wanted to experiment with different languages to achieve my goals. By the time I went to university, I was already relatively familiar with Java, C# and JavaScript (due to the similarities UnityScript holds to it). \
In my time at university, I did modules where I was required to work in Java, Python, Swift, C#/.NET and MySQL. I also gained experience in cybersecurity through exposure to Kali Linux, where I was taught how to properly assess risk and how some of the more common cyber-attacks are performed. Learning this combination of technologies has provided me with what I feel is a strong foundation to my career, as it is broad and detailed enough that I can apply my skills to a number of different roles, as well as providing me with more flexibility in what I am able to learn. In my final year project, I decided to further expand that knowledge by learning about React and Node.js, while trying out a non-relational database in MongoDB. This project also exposed me to GraphQL, which I found invaluable in making my client-server communication more straightforward (which I needed as a beginner), as well as requiring me to work with REST APIs to gather data from external sources. I have continued to reinforce that web-development knowledge in my personal projects since leaving university, as well as laying the foundation of teaching myself C++ to start a longer-term project of building a graphics engine with OpenGL.\
In my current role with Wiley Edge, I am working on site with Genesis Global. This employment began with a two-month bootcamp where we covered some Java/OOP fundamentals, spent time looking at how to best use relational databases (for those who weren’t already familiar with these concepts), and were also educated on how financial markets work. This prepared me well for my placement role, as Genesis Global creates software specifically for financial markets. At Genesis, my work is focused on Java development, but as I spent more time in the team I was quickly given more responsibility. Working in a CI/CD environment, I regularly had to adapt to supplement the roles of business-analyst and tester as well as being a developer in order to meet deadlines and deliver reliable and performant functionality to the clients. I also went out of my way to build a generic testing tool that could be used by the entire company, which utilised the event-driven architecture that is inherent to all of the company’s products in order to facilitate full end-to-end testing. This even meant building a testing language of my own which is similar to Cucumber (I called it Courgette) so that testers are empowered to write their own test scenarios without the assistance of a developer. Servers are hosted with AWS, providing applications built with microservices. I quickly became accustomed to that workflow as I was given more responsibility in server maintenance (mainly when it came to enabling clients to test new features on UAT servers). In the project I was specifically working on as my actual role in the company, we used RxDB to interface with a FoundationDB wrapper and used JUnit combined with Mockito for our unit tests.\
I have gained a considerable amount of experience in the software development lifecycle during my year and a half of experience in the industry, touching significantly more areas than I expected outside of just writing code. I look forward to hopefully working on more projects which require me to venture even further outside of my comfort zone. The constant learning is what makes this career appeal to me so much in the first place, and that appeal is strengthened by opportunities to make an impact on the wider world.\
"

export default function Home() {
	return (
		<>
			<Welcome/>
			<ContentBox className='homeImage' img={me} imgAlt='Initial D'/>
			<ContentBox>
				<p>{ABOUT_TEXT}</p>
			</ContentBox>
		</>
	)
}
